# Generated by Django 4.2.7 on 2026-02-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('contact', models.CharField(max_length=50)),
                ('specialities', models.JSONField(default=list)),
                ('hospital_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('trust', 'Trust'), ('premium', 'Premium'), ('unknown', 'Unknown')], default='private', max_length=20)),
                ('rating', models.FloatField(default=0.0)),
                ('acceptedSchemes', models.JSONField(default=list)),
                ('base_cost_factor', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
