# Generated by Django 4.2.7 on 2026-02-12 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='emergency_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='facilities',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='hospital',
            name='icu_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('experience_years', models.IntegerField(default=0)),
                ('is_head_doctor', models.BooleanField(default=False)),
                ('consultation_days', models.CharField(default='Mon-Sat', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='core.hospital')),
            ],
            options={
                'ordering': ['-is_head_doctor', 'name'],
            },
        ),
    ]
