# Generated by Django 4.2.7 on 2026-02-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hospital_emergency_beds_hospital_facilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='ambulance_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
