# Generated by Django 4.2.7 on 2026-02-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_lab_report_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='facility_category',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('xray', 'X-Ray Center'), ('mri', 'MRI Center'), ('ct_scan', 'CT Scan Center'), ('physiotherapy', 'Physiotherapy Center')], default='hospital', max_length=20),
        ),
    ]
