# Generated by Django 4.2.7 on 2026-02-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hospital_facility_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='facility_category',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('xray', 'X-Ray Center'), ('mri', 'MRI Center'), ('ct_scan', 'CT Scan Center'), ('physiotherapy', 'Physiotherapy Center'), ('pathology', 'Pathology Lab')], default='hospital', max_length=20),
        ),
    ]
